spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    prefix: classpath:/tempates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    content-type: text/html
    cache: false

mybatis:
  type-aliases-package: com.jk.pojo
  mapper-locations: classpath:mapper/*.xml





















